### ISSUE TITLE
Block Breaking: collisions and statuses

### ISSUE THREAD

**Issue by dreammelter** [dreammelter/NVD23#4]
This is just for the logic side of things.

**Task overview:**
- [ ] Verify the paddle moves as expected and collisions are in place (the ball should ricochet off paddles, blocks, characters, and walls.)
- [ ] When the player deflects an enemy ball with their paddle, it is pacified
- [ ] When an enemy deflects the player's ball, it becomes dangerous
- [ ] The ball maintains its speed and super status during the "team switch"

Break items out into separate issues as needed.

For the enemy one: you may have to test with a that isn't attached to anything or wait until the enemies are upgraded. (Or fake it: put the paddle in front of the enemy while testing.)

**Comment by dreammelter** [comment]
See #27.
